lineas.prod.jdbcUrl=
lineas.prod.username=
lineas.prod.password=
lineas.prod.driverClassName=
lineas.prod.maximumPoolSize=5

lineas.ccard.jdbcUrl=
lineas.ccard.username=
lineas.ccard.password=
lineas.ccard.driverClassName=
lineas.ccard.maximumPoolSize=5
